version: '3.8'
services:
  apiservice:
    image: ${ECR_REPOSITORY_URI}/cleanaspire-api:${IMAGE_TAG}
    # Build is defined in docker-compose.override.yml for local development
    environment:
      - ASPNETCORE_ENVIRONMENT=${APISERVICE_ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__DBProvider=postgresql
      - DatabaseSettings__ConnectionString=Server=acquanalise-test.c9uc6w24mh3v.us-east-1.rds.amazonaws.com;Database=CleanAspire;User Id=postgres;Password=acquanalise123;Port=5432
      - ClientBaseUrl=https://app.acquanalise.com
      - AllowedCorsOrigins=https://app.acquanalise.com,http://localhost:80,http://localhost
    ports:
      - "${APISERVICE_PORT_HTTP:-8080}:8080"
    logging:
      driver: ${LOGGING_DRIVER:-json-file}
      options:
        awslogs-group: ${AWS_LOGS_GROUP:-cleanaspire-logs}
        awslogs-region: ${AWS_REGION:-us-east-1}
        awslogs-stream-prefix: apiservice
        awslogs-create-group: "true"
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILES:-3}
    deploy:
      resources:
        limits:
          cpus: '${APISERVICE_CPU_LIMIT}'
          memory: ${APISERVICE_MEMORY_LIMIT}
  
  blazorweb:
    image: ${ECR_REPOSITORY_URI}/cleanaspire-webapp:${IMAGE_TAG}
    # Build is defined in docker-compose.override.yml for local development
    environment:
      - ASPNETCORE_ENVIRONMENT=${BLAZORWEB_ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:80
      - ClientAppSettings__ServiceBaseUrl=http://apiservice:8080
    ports:
      - "${BLAZORWEB_PORT_HTTP:-80}:80"
    depends_on:
      - apiservice
    logging:
      driver: ${LOGGING_DRIVER:-json-file}
      options:
        awslogs-group: ${AWS_LOGS_GROUP:-cleanaspire-logs}
        awslogs-region: ${AWS_REGION:-us-east-1}
        awslogs-stream-prefix: blazorweb
        awslogs-create-group: "true"
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILES:-3}
    deploy:
      resources:
        limits:
          cpus: '${BLAZORWEB_CPU_LIMIT}'
          memory: ${BLAZORWEB_MEMORY_LIMIT}